### ISSUE TITLE
"Ranks" section lists the rank Event Coordinator as "Senior Referee"

### ISSUE THREAD

**Issue by samthecat** [MasterEjay/Overcast-Wiki#61]
![capture](https://cloud.githubusercontent.com/assets/10585916/8272339/2e3cf35a-180c-11e5-9cf3-a6b02c7b2a4d.PNG)

**Comment by EricZeiberg** [comment]
This project is no longer updated.

**Comment by samthecat** [comment]
What do you mean by that? The Overcast Wiki is no longer being developed?

**Comment by EricZeiberg** [comment]
Yes this is correct. I am no longer working on the Overcast Wiki because I dont want to waste my time on a server that is dead

**Comment by samthecat** [comment]
Okay? The server is in no way "dead" though it's your decision.

**Comment by EricZeiberg** [comment]
Well, it barely hits 800 players at peak times, and I remember when it used to reach 2000, so....

**Comment by samthecat** [comment]
And in your mind that constitutes as dead? I flat out disagree.

**Comment by EricZeiberg** [comment]
Ok, well lets see:
All devs left / went AWOL except for Cubist
Many famous players left
The server is obviously in decline since a drop from 2000 to 800 is more than 50%

Anyway, the point is, this project will no longer be maintained, so if you want to change something, click dat fork button or go use matic's wiki.

**Comment by hfoxy** [comment]
Even if it's not completely dead yet, it's most definitely dying. A lot of the old Overcast community members lost interest in the server, due to a lack of development, false promises and various other reasons.
